apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: abyss
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Abyss test project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/adriamanu/argocd-demo'
  # Only permit applications to deploy to the abyss namespace in the same cluster
  destinations:
  - namespace: abyss
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to abyss
    policies:
    - p, proj:abyss:read-only, applications, get, abyss/*, allow
    groups:
    - my-oidc-group