apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abyss-app
  name: abyss-app
  namespace: abyss
spec:
  replicas: 4
  selector:
    matchLabels:
      app: abyss-app
  strategy: {}
  template:
    metadata:
      labels:
        app: abyss-app
    spec:
      containers:
      - image: nginx:1.21.4
        name: nginx
        resources: {}
status: {}
